owner: kishikawakatsumi
repo: status.swiftdevelopers.jp

sites:
  - name: swiftdevelopers.jp
    url: https://swiftdevelopers.jp
  - name: archive.swiftdevelopers.jp
    url: https://archive.swiftdevelopers.jp/

status-website:
  cname: status.swiftdevelopers.jp
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Swift Developers Japan Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/20 * * * *"
  
